name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: yarn install

    - name: Run TypeScript Compiler
      run: yarn tsc

    - name: Build project
      run: yarn build

    - name: Run ESLint
      run: yarn lint
